In [4]:
#建立list

a = [1, 3, 5, 7, 9]
a*2


b = [2, 4, 6, 8, 10]
a+b

result = []
for i in range(5):
    result.append(a[i] + b[i])

result

#in list calculation, for in logic is required.

[3, 7, 11, 15, 19]

In [4]:
import numpy as np
#透過list建立ndArray


a_array = np.array([1, 3, 5, 7, 9])
a_array*2
#可做陣列運算

b_array = np.array([2, 4, 6, 8, 10])
a_array + b_array


array([ 3,  7, 11, 15, 19])

In [5]:
#使用python建立亂數
import random

[random.randint(50,100) for _ in range(5)]

[66, 60, 98, 95, 57]

In [7]:
import numpy as np
np.random.randint(50, high=100, size = 5)

array([64, 83, 66, 72, 77])

In [6]:
import numpy as np
np.random.randint(50, high=100, size = (50,5))

array([[98, 91, 58, 91, 70],
       [66, 72, 89, 92, 60],
       [67, 78, 78, 58, 94],
       [85, 72, 89, 65, 68],
       [73, 91, 74, 76, 59],
       [59, 91, 76, 64, 68],
       [80, 59, 64, 61, 89],
       [95, 75, 93, 61, 96],
       [53, 87, 52, 75, 85],
       [98, 51, 57, 85, 90],
       [88, 73, 95, 98, 73],
       [86, 98, 81, 50, 52],
       [71, 69, 77, 88, 79],
       [54, 63, 81, 74, 54],
       [55, 55, 58, 53, 63],
       [56, 97, 64, 70, 97],
       [55, 92, 58, 87, 87],
       [85, 99, 68, 99, 95],
       [82, 98, 93, 98, 76],
       [89, 65, 55, 66, 64],
       [76, 54, 93, 72, 87],
       [85, 67, 58, 75, 97],
       [78, 91, 61, 78, 78],
       [84, 50, 99, 54, 92],
       [76, 64, 50, 70, 60],
       [67, 52, 67, 87, 63],
       [93, 81, 87, 67, 59],
       [66, 57, 70, 89, 53],
       [62, 75, 78, 98, 85],
       [97, 74, 99, 74, 89],
       [53, 95, 97, 95, 51],
       [94, 51, 68, 73, 87],
       [86, 68, 58, 50, 90],
       [68, 71, 93, 69, 89],
       [56, 87